version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=microservices
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3308:3306'
    expose:
      - '3306'

  book-service:
    build:
      context: ../../back-end/book-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 5556:5555
    depends_on:
      - database-mysql

  borrow-service:
    build:
      context: ../../back-end/borrow-book-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 1235:1234

  message-service:
    build:
      context: ../../back-end/message-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 7778:7777

  user-service:
    build:
      context: ../../back-end/user-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3333:3333

  nginx:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ../../front-end/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - book-service
      - borrow-service
      - message-service
      - user-service
    # docker compose -p huyhoang-nginx up -d

    # docker compose -p hoidanit-nodejs-mysql up -d

    # docker compose -p borrow-book up -d